const GET_MARSROVER_PHOTOS="GET_MARSROVER_PHOTOS";
const TRANSLATE_APOD_LASTD="TRANSLATE_APOD_LASTD";
const SELECT_MARSROVER_VIEW="SELECT_MARSROVER_VIEW";
const GET_TRANSLATED_APOD_LASTD='GET_TRANSLATED_APOD_LASTD';
const TOGGLE_LANG="TOGGLE_LANG";
 export const actionType={
    GET_MARSROVER_PHOTOS,
    TRANSLATE_APOD_LASTD,
    SELECT_MARSROVER_VIEW,
    GET_TRANSLATED_APOD_LASTD,
    TOGGLE_LANG 
}