const CONFIRM_HINT_READ_BUTTON="CONFIRM_HINT_READ_BUTTON";
const DONTSHOWMORE_CHECKBOX_ACTION="DONTSHOWMORE_CHECKBOX_ACTION";
 

 export const actionType={
    CONFIRM_HINT_READ_BUTTON,
    DONTSHOWMORE_CHECKBOX_ACTION,
     
}