const CONFIRM_HINT_READ_BUTTON="CONFIRM_HINT_READ_BUTTON";
const DONTSHOWMORE_CHECKBOX_ACTION="DONTSHOWMORE_CHECKBOX_ACTION";
const CONFIRM_HINT_READ_BUTTON_SLIDER="CONFIRM_HINT_READ_BUTTON_SLIDER";
const DONTSHOWMORE_CHECKBOX_ACTION_SLIDER="DONTSHOWMORE_CHECKBOX_ACTION_SLIDER";
const TOGGLE_HINTVIEW_GLOBAL='TOGGLE_HINTVIEW_GLOBAL';

 export const actionType={
    CONFIRM_HINT_READ_BUTTON,
    DONTSHOWMORE_CHECKBOX_ACTION,
    CONFIRM_HINT_READ_BUTTON_SLIDER,
    DONTSHOWMORE_CHECKBOX_ACTION_SLIDER,
     TOGGLE_HINTVIEW_GLOBAL
}