const GET_APOD_LASTD="GET_APOD_LASTD";
const TRANSLATE_APOD_LASTD="TRANSLATE_APOD_LASTD";
const SELECT_APOD_VIEW="SELECT_APOD_VIEW";
const GET_TRANSLATED_APOD_LASTD='GET_TRANSLATED_APOD_LASTD';
const TOGGLE_LANG="TOGGLE_LANG";
const SLIDER_NEXT="SLIDER_NEXT";
const SLIDER_BACK="SLIDER_BACK";
const OPEN_SFS="OPEN_SFS";


 export const actionType={
    GET_APOD_LASTD,
    TRANSLATE_APOD_LASTD,
    SELECT_APOD_VIEW,
    GET_TRANSLATED_APOD_LASTD,
    TOGGLE_LANG ,
    SLIDER_NEXT,
    SLIDER_BACK,
    OPEN_SFS
}